# Generated by Django 3.0.6 on 2020-06-02 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('data_registo', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=30)),
                ('tipo_user', models.IntegerField(default=1)),
                ('criado_por', models.IntegerField()),
            ],
        ),
    ]
