# Generated by Django 3.0.6 on 2020-06-05 16:46

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/media/img/placeholder.jpg', storage=django.core.files.storage.FileSystemStorage(location='media/img/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='criado_por',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_registo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_user',
            field=models.CharField(default='base', max_length=30),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('video', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/videos/'), upload_to=django.core.files.storage.FileSystemStorage(location='videos/'))),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
