# Generated by Django 3.0.6 on 2020-06-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20200605_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/media/img/placeholder.jpg', upload_to='./img/'),
        ),
    ]
