# Generated by Django 3.0.6 on 2020-06-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_auto_20200605_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C:/videos/'),
        ),
    ]
