# Generated by Django 3.0.6 on 2020-06-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_auto_20200608_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\newapp\\media/videos/'),
        ),
    ]
