# Generated by Django 3.0.6 on 2020-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0023_auto_20200608_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\videos/'),
        ),
    ]
