# Generated by Django 3.0.6 on 2020-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_auto_20200608_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\img', upload_to='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\img'),
        ),
    ]
