# Generated by Django 3.0.6 on 2020-06-08 14:56

from django.db import migrations, models
import newapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_video_tipo_ficheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\videos', validators=[newapp.validators.valida_video]),
        ),
    ]
