# Generated by Django 3.0.6 on 2020-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0032_auto_20200608_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('pdf', models.FileField(upload_to='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\pdf')),
            ],
        ),
    ]
