# Generated by Django 3.0.6 on 2020-06-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0034_auto_20200608_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
