# Generated by Django 3.0.6 on 2020-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0041_auto_20200617_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
