# Generated by Django 3.0.6 on 2020-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0042_auto_20200617_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
