# Generated by Django 3.0.6 on 2020-06-24 15:56

from django.db import migrations, models
import newapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0043_auto_20200617_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media\\img\\placeholder.jpg', upload_to='media\\img', validators=[newapp.validators.valida_img]),
        ),
    ]
