# Generated by Django 3.0.6 on 2020-06-25 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0045_auto_20200624_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('feito', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\img\\placeholder.jpg', upload_to='C:\\Users\\sergy.kostenko\\Desktop\\apiserver\\server\\media\\img', validators=[newapp.validators.valida_img]),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('tempo', models.TimeField()),
                ('duels', models.ManyToManyField(to='newapp.Duel')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('url', models.URLField()),
                ('popularidade', models.IntegerField(default=0)),
                ('duel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Duel')),
            ],
        ),
        migrations.AddField(
            model_name='duel',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
