# Generated by Django 3.0.6 on 2020-06-25 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0046_auto_20200625_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='tempo',
        ),
        migrations.AddField(
            model_name='duel',
            name='criado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='result',
            name='fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='result',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
