# Generated by Django 3.0.6 on 2020-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0047_auto_20200625_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
