# Generated by Django 3.0.6 on 2020-06-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0048_duel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
