# Generated by Django 3.0.6 on 2020-07-01 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0052_auto_20200630_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
