# Generated by Django 3.0.6 on 2020-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0058_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='iteration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
