# Generated by Django 3.0.6 on 2020-07-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0060_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
