# Generated by Django 3.1.5 on 2021-01-16 19:57

from django.db import migrations, models
import newapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0061_auto_20200715_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='C:\\Users\\Sergiy\\Desktop\\Django_apiserver\\apiserver\\server\\media\\img\\placeholder.jpg', upload_to='C:\\Users\\Sergiy\\Desktop\\Django_apiserver\\apiserver\\server\\media\\img', validators=[newapp.validators.valida_img]),
        ),
    ]
